import { Waveshare-ESP32-S3-RLCD-4-2} from "constants.slint";
export component App inherits Window {
    width: Waveshare-ESP32-S3-RLCD-4-2.screenWidth;
    height: Waveshare-ESP32-S3-RLCD-4-2.screenHeight;

    Rectangle {
        background: #1f2937;

        Text {
            x: 16px;
            y: 16px;
            text: "ESP32-S3 + Slint + Rust";
            color: white;
            font-size: 18px;
        }

        Text {
            x: 16px;
            y: 48px;
            text: "compile-only skeleton";
            color: #cbd5e1;
            font-size: 14px;
        }
    }
}