import { Waveshare-ESP32-S3-RLCD-4-2 } from "constants.slint";
export component App inherits Window {
    width: Waveshare-ESP32-S3-RLCD-4-2.screenWidth;
    height: Waveshare-ESP32-S3-RLCD-4-2.screenHeight;

    in property <string> current-time: "--:--";
    in property <string> current-second: "--";
    in property <string> current-date: "2000-01-01 Mon";
    in property <int> battery: 100;
    background: white;
    Rectangle {
        width: parent.width;
        height: parent.height;
        background: white; 
        // ===== 顶栏 =====
         Text {
            x: 16px;
            y: 12px;
            text: current-date;
            color: black;
            font-size: 14px;
        }

        // ===== 电池状态 =====
        Rectangle {
            private property <int> battery-len:50;
            border-width: 2px;
            x: parent.width - 76px;
            y: 12px;
            width: battery-len * 1px + 4px;
            height: 20px;
            border-color: black;
            background: white;
            Rectangle {
                x: parent.border-width;
                y: parent.border-width;
                width: (battery * parent.battery-len / 100) * 1px;
                height: parent.height - 2 * parent.border-width;
                background: black;
            }
        }

        Text {
            x: parent.width - 130px;
            y: 14px;
            text: battery + "%";
            color: black;
            font-size: 14px;
        } 
        // ===== 分隔线 ===== 
        Rectangle {
            x: 16px;
            y: 44px;
            width: parent.width - 32px;
            height: 2px;
            background: black;
        } 
        // ===== 时间 ===== 
        Text {
            horizontal-alignment: center;
            x: 0px;
            y: 90px;
            width: parent.width;
            text: current-time;
            color: black;
            font-size: 88px;
            font-weight: 700;
        }

        Text {
            horizontal-alignment: center;
            x: 0px;
            y: 180px;
            width: parent.width;
            text: current-second;
            color: black;
            font-size: 32px;
        } 
        // ===== 底部状态 ===== 
        Rectangle {
            x: 40px;
            y: 255px;
            width: parent.width - 80px;
            height: 2px;
            background: black;
        }

        Text {
            x: 0px;
            y: 268px;
            width: parent.width;
            horizontal-alignment: center;
            text: "ESP32-S3 CLOCK";
            color: black;
            font-size: 14px;
        }
    }
}
